In [ ]:
# SVM  best 1000 cu CountVectorizer, fara normalizare

In [1]:
from sklearn import preprocessing
from sklearn import svm
from sklearn.metrics import f1_score
import numpy as np

In [2]:
def normalize_data(train_data, test_data, type=None):
    scaler = None
    if type == 'standard':
        scaler = preprocessing.StandardScaler()


    elif type == 'l1':
        scaler = preprocessing.Normalizer(norm='l1')

    elif type == 'l2':
        scaler = preprocessing.Normalizer(norm='l2')

    if scaler is not None:
        scaler.fit(train_data)
        scaled_train_data = scaler.transform(train_data)
        scaled_test_data = scaler.transform(test_data) 
        return (scaled_train_data, scaled_test_data)
    else:
        print("No scaling was performed. Raw data is returned.")
        return (train_data, test_data)

In [3]:
def accuracy_score(y_true, y_pred):
    return (y_true == y_pred).mean()
#train_labels = train_labels.astype(int)

In [4]:
def get_sentence(data):
    new_data = []
    
    for item in data:
        new_data.append(item[1])
        
    return np.array(new_data)

In [5]:
def get_labels(data):
    new_data = []
    
    for item in data:
        new_data.append(item[1])
    return np.array(new_data)

In [17]:
# load data
training_data = np.genfromtxt('data_aliens/train_samples.txt', dtype='str', comments='\\\\\\\\\\\\\\\\', delimiter='\t', invalid_raise = False)
training_labels = np.loadtxt('data_aliens/train_labels.txt', dtype='int')

validation_data = np.genfromtxt('data_aliens/validation_samples.txt', dtype='str', comments='\\\\\\\\\\\\\\\\', delimiter='\t', invalid_raise = False)
validation_labels = np.loadtxt('data_aliens/validation_labels.txt', dtype='int')

x_train = get_sentence(training_data)
y_train = get_labels(training_labels)

x_valid = get_sentence(validation_data)
y_valid = get_labels(validation_labels)

print(validation_data.shape)

# print(training_data)
# print(get_labels(training_labels))

(5000, 2)


In [12]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(lowercase = False, max_features=1000, strip_accents=None, min_df=1, stop_words=None)
X_train_counts = count_vect.fit_transform(x_train)
X_test_counts = count_vect.fit_transform(x_valid)

print(X_train_counts.shape)

print(X_train_counts.toarray())

train_data = X_train_counts.toarray()
test_data = X_test_counts.toarray()

#print(X_test_counts.shape)
#count_vect.get_feature_names_out()


(10000, 1000)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
svm_classifier = svm.SVC(C=1, kernel='linear')

svm_classifier.fit(X_train_counts, y_train)
predicted = svm_classifier.predict(test_data)

print(accuracy_score(predicted, y_valid))

0.3162


In [16]:
print(predicted)
print(predicted.shape)
print(x_valid.shape)

[1 2 2 ... 3 1 2]
(5000,)
(5000,)
