In [1]:
# SVM  best 1000 cu CountVectorizer, fara normalizare

In [2]:
from sklearn import preprocessing
from sklearn import svm
from sklearn.metrics import f1_score
import numpy as np

In [3]:
def normalize_data(train_data, test_data, type=None):
    scaler = None
    if type == 'standard':
        scaler = preprocessing.StandardScaler()


    elif type == 'l1':
        scaler = preprocessing.Normalizer(norm='l1')

    elif type == 'l2':
        scaler = preprocessing.Normalizer(norm='l2')

    if scaler is not None:
        scaler.fit(train_data)
        scaled_train_data = scaler.transform(train_data)
        scaled_test_data = scaler.transform(test_data) 
        return (scaled_train_data, scaled_test_data)
    else:
        print("No scaling was performed. Raw data is returned.")
        return (train_data, test_data)

In [4]:
def accuracy_score(y_true, y_pred):
    return (y_true == y_pred).mean()
#train_labels = train_labels.astype(int)

In [5]:
def get_sentence(data):
    new_data = []
    
    for item in data:
        new_data.append(item[1])
        
    return np.array(new_data)

In [6]:
def get_labels(data):
    new_data = []
    
    for item in data:
        new_data.append(item[1])
    return np.array(new_data)

In [7]:
# load data
training_data = np.genfromtxt('data_aliens/train_samples.txt', dtype='str', comments='\\\\\\\\\\\\\\\\', delimiter='\t', invalid_raise = False)
training_labels = np.loadtxt('data_aliens/train_labels.txt', dtype='int')

validation_data = np.genfromtxt('data_aliens/validation_samples.txt', dtype='str', comments='\\\\\\\\\\\\\\\\', delimiter='\t', invalid_raise = False)
validation_labels = np.loadtxt('data_aliens/validation_labels.txt', dtype='int')

x_train = get_sentence(training_data)
y_train = get_labels(training_labels)

x_valid = get_sentence(validation_data)
y_valid = get_labels(validation_labels)

print(validation_data.shape)

# print(training_data)
# print(get_labels(training_labels))

(5000, 2)


In [13]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(lowercase = False, max_features=5000, strip_accents=None, min_df=1, stop_words=None)
X_train_counts = count_vect.fit_transform(x_train)
X_test_counts = count_vect.fit_transform(x_valid)

print(X_train_counts.shape)

print(X_train_counts.toarray())

train_data = X_train_counts.toarray()
test_data = X_test_counts.toarray()

#print(X_test_counts.shape)
#count_vect.get_feature_names_out()


(10000, 5000)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
# Normalizare a datelor

scale_train, scale_validation = normalize_data(train_data, test_data, "l2")

In [18]:
svm_classifier = svm.SVC(C=5, kernel='linear')

svm_classifier.fit(scale_train, y_train)
predicted = svm_classifier.predict(scale_validation)

print(accuracy_score(predicted, y_valid))

0.376


In [16]:
print(predicted)
print(predicted.shape)
print(x_valid.shape)

[2 1 1 ... 1 3 2]
(5000,)
(5000,)


In [17]:
import csv

def write_prediction(test_data, predicted):
    header = ['id', 'label']
    
    data = []
    
    for i in range(0, len(test_data)):
        id = int(test_data[i][0])
        label = int(predicted[i])
        
        data.append([id, label])
        
    with open('submission', 'w', encoding='UTF8') as f:
        writer = csv.writer(f)
        writer.writerow(header)
        
        for item in data:
            writer.writerow(item)

In [20]:
# Citire date test

test_data_init = np.genfromtxt('data_aliens/test_samples.txt', dtype='str', comments='\\\\\\\\\\\\\\\\', delimiter='\t', invalid_raise = False)

x_test = get_sentence(test_data_init)

X_test_counts = count_vect.fit_transform(x_test)

test_data = X_test_counts.toarray()

scale_test, scale_test = normalize_data(test_data, test_data, "l2")

In [21]:
predicted = svm_classifier.predict(scale_test)

In [22]:
write_prediction(test_data_init, predicted)

In [23]:
print(test_data_init.shape)
print(predicted.shape)

(5000, 2)
(5000,)
